# Generated by Django 5.2.14 on 2026-06-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="salary_type",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("daily", "Daily")],
                default="monthly",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="join_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
