# Generated by Django 5.2.14 on 2026-06-03 06:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people_app", "0002_employee_salary_type_alter_employee_join_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="salary_type",
        ),
        migrations.AlterField(
            model_name="employee",
            name="join_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
