# Generated by Django 5.2.14 on 2026-06-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("people_app", "0003_remove_employee_salary_type_alter_employee_join_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
