# Generated by Django 5.2.6 on 2026-08-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0007_customer_ledger_and_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'ordering': ('month',)},
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid'), ('Partial', 'Partial')], default='Unpaid', max_length=20),
        ),
    ]
