# Generated by Django 6.0.7 on 2026-08-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0008_alter_employeesalary_options_employeesalary_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.PositiveIntegerField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('token',),
            },
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='employeesalary',
            name='status',
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='settled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='settled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
