# Generated by Django 5.2.6 on 2026-08-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people_app', '0009_walkingcustomer_remove_employeesalary_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetransaction',
            name='transaction_type',
            field=models.CharField(choices=[('taken', 'Cash Taken'), ('deposit', 'Cash Deposit'), ('salary_payment', 'Salary Payment')], max_length=20),
        ),
    ]
