# Generated by Django 5.2.14 on 2026-05-30 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="pack_size",
            field=models.IntegerField(default=1, help_text="1 crate = ? pieces"),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
