# Generated by Django 5.2.14 on 2026-05-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0002_fooditem_pack_size_alter_fooditem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="pack_size",
            field=models.IntegerField(default=1, help_text="1 crate = 6 pieces"),
        ),
    ]
