# Generated by Django 6.0.7 on 2026-08-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_order_customer_name_order_customer_phone_and_more'),
        ('people_app', '0009_walkingcustomer_remove_employeesalary_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='walking_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='walking_orders', to='people_app.walkingcustomer'),
        ),
        migrations.CreateModel(
            name='WalkingCustomerLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('order', 'Order charge'), ('payment', 'Payment received'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walking_ledger_entries', to='core_app.order')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='walking_ledger_entry', to='core_app.payment')),
                ('walking_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='people_app.walkingcustomer')),
            ],
            options={
                'ordering': ('occurred_at', 'id'),
                'indexes': [models.Index(fields=['walking_customer', 'occurred_at'], name='core_app_wa_walking_5afb2c_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'entry_type'), name='one_walking_order_charge_per_order_type')],
            },
        ),
    ]
