# Generated by Django 5.2.14 on 2026-05-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0003_alter_fooditem_pack_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="pack_size",
            field=models.IntegerField(default=1, help_text="1 crate = ? pieces"),
        ),
    ]
