# Generated by Django 5.2.6 on 2026-08-05 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0003_order_walking_customer_walkingcustomerledgerentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermanualledgerentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_order_entries', to='core_app.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_snapshot',
            field=models.ImageField(blank=True, null=True, upload_to='manual_orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='manual_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
