# Generated by Django 5.2.14 on 2026-05-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0004_alter_fooditem_pack_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="pack_size",
        ),
        migrations.AddField(
            model_name="fooditem",
            name="piece_per_carton",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="piece_per_crate",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="piece_per_pack",
            field=models.IntegerField(default=1),
        ),
    ]
