# Generated by Django 5.2.14 on 2026-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core_app",
            "0005_remove_fooditem_pack_size_fooditem_piece_per_carton_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="piece_per_carton",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="piece_per_crate",
        ),
        migrations.RemoveField(
            model_name="fooditem",
            name="piece_per_pack",
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
