# Generated by Django 5.2.14 on 2026-06-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0006_remove_fooditem_piece_per_carton_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fooditem",
            name="total_sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
