# Generated by Django 5.2.14 on 2026-06-02 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0007_fooditem_created_at_fooditem_total_sold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
