# Generated by Django 5.2.14 on 2026-06-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0008_alter_fooditem_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=8
            ),
            preserve_default=False,
        ),
    ]
