# Generated by Django 5.2.14 on 2026-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_app", "0010_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("Pending", "Pending"), ("Cleared", "Cleared")],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
