# Generated by Django 6.0.7 on 2026-07-30 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0012_customer_ledger_and_audit'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customerledgerentry',
            new_name='core_app_cu_custome_4c26ce_idx',
            old_name='core_app_custome_1e345c_idx',
        ),
    ]
