# Generated by Django 6.0.7 on 2026-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0013_rename_core_app_custome_1e345c_idx_core_app_cu_custome_4c26ce_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='pieces_per_unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='total_pieces',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('carton', 'Carton')], default='unit', max_length=20),
        ),
    ]
