# Generated by Django 6.0.7 on 2026-07-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0014_stocktransaction_pieces_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='custom_unit_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='default_unit',
            field=models.CharField(choices=[('unit', 'Piece'), ('pack', 'Pack'), ('box', 'Box'), ('carton', 'Carton'), ('bottle', 'Bottle')], default='unit', max_length=20),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='pieces_per_box',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='pieces_per_carton',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='pieces_per_pack',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
